spring:
  application:
    name: eureka-server
server:
  port: 7761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.0.26:${server.port}/eureka/,http://172.16.0.26:${server.port}/eureka/